name: Build
on: [push, pull_request]
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Check clippy
      run: cargo clippy -- -Dwarnings
    - name: Test
      run: cargo test --release
    - name: Build
      run: cargo build --release

  build_windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: cargo test --release
    - name: Build
      run: cargo build --release
