on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
name: Create Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Install x11 dev
        run: sudo apt-get install libx11-dev
      - uses: actions/checkout@v2
      - run: cargo login ${CRATES_IO_TOKEN}
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      - name: Publish lib
        run: cargo publish
        working-directory: ./lib
      - name: Sleep for 15 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: "15s"
